### PR TITLE
Updated parameters

### PR DESCRIPTION
**Pull request by thomasthe1st**
corrected stunnel.sh parameter and file names. At least for my NAS TS-412 with latest firmware those were the correct parameters.

### CODE REVIEW

**Comment by yoanm** [comment]
I just checked with mine (TS-231P) and script worked well.
What is your OS version ?

I tried with `4.5.4.1787` and `4.5.4.1800` versions, no issue, new certificate is correctly taken into account.

**Comment by yoanm** [comment]
After checks, it seems your NAS @thomasthe1st is restricted to `4.3.3.1799` (cf https://www.qnap.com/fr-fr/download?model=ts-412&category=firmware), so it should work too (it should, I forgot when I started to use that script, so maybe your version has some differences).

There is maybe a misunderstood here, script was modified in order to update the certificate used for HTTPS, not for stunnel's certificate (initially, it was made for STunnel cert if I recall correctly).
Maybe you what you want is to update Stunnel cert instead ?

**Comment by thomasthe1st** [comment]
well in fact I want to use it for HTTPS as well. I recognized however meanwhile that my suggested changes are not enough. The initial page is still using another certificate and only after I log in the certificate which I want to put onto the box is presented which is kind of weird as if it is using two different HTTP servers one for users which are logged in and one for the login page. So in a nutshell to me it seems as if my NAS has a different software compared to yours. The version is however the one you mentioned above.

**Comment by yoanm** [comment]
Hoo ok, so nothing to do here IMO.
I'm facing the same issue on my side. It happens also if you update the certificate from web UI.
When certificate is updated, in case you already have a browser tab opened with NAS URL, it will look like if certificate hasn't been updated, even if you open a new tab or reload the existing one.
But if you open the NAS URL on either a "private navigation" tab or on another browser, the updated certificate is used.

I guess issue is something around browser caching the certificate, not something on QNAP side.

Let me know if we speak about the same issue, if it's the case, that PR can be closed.

**Pull request closed without merging**
